### ISSUE TITLE
Notchmeister window opens unprompted on all desktops when multiple desktops are open

### ISSUE THREAD

**Issue by dmalachi** [chockenberry/Notchmeister#11]
Summary:
If the user has multiple desktops open, the Notchmeister window will randomly open on all desktops; this happens even when the user has selected 'Assign to...All Desktops' or 'Assign to...This Desktop' in Notchmeister options.

Steps to Reproduce:
1. Open multiple desktops
2. Open Notchmeister
3. After a few minutes, swipe to other desktops

Expected Behavior: 
Notchmeister window shouldn't open without user input; if it does open, it should be on assigned desktop only

Actual Behavior: 
Notchmeister window opens unprompted on all desktops multiple times a day

App version:
v1.0 (15) 

System Version:
macOS Monterey 

Notes:
See attached screen recording
https://user-images.githubusercontent.com/70352484/148466625-a69d2591-7834-4886-81ff-8456cf5aaa21.mov

**Comment by chockenberry** [comment]
It's not clear from the video what is causing the window to open unprompted.

Notchmeister's window is configured to appear in all spaces (effectively ignoring any assigned desktop). The thinking here is that the notch appears in every space, so the window that configures it should as well.

**Comment by danielpunkass** [comment]
I'm pretty sure the behavior described here "opening unprompted" is a natural consequence of the use of Spaces and Notchmeister's window being marked as having a "transient" collection behavior. With this collection behavior I think even if the window had previously been closed, activing a new Space will cause the window to be made visible again.

**Comment by dmalachi** [comment]
I think @danielpunkass's description most closely matches the behavior I'm seeing. I love Notchmeister as it is so much fun, but the window popping up pretty frequently is a bummer. Although I'm not sure how involved this is, it seems like it would be addressed by making a 'Preferences' menu item where the user could 'set it and forget it.' Or add an option to 'Don't show this window again' after which the user could change effects by secondary clicking on the app icon. There may be other solutions as well, but it seems the current behavior assumes that the user wants to change the effect every time they swipe to a new desktop, which I feel should be mitigated somehow.

**Comment by chockenberry** [comment]
@dmalachi I'm curious if the latest TestFlight build solves this problem. Part of the problem with transient windows is that they get "activated".

With the new "Hide Dock icon" feature, there's no app to activate. In theory, this will prevent the settings window from appearing as spaces are switched.

Here's the TestFlight: https://testflight.apple.com/join/Nj8aKRvl

**Comment by dmalachi** [comment]
This TestFlight is for an app called Tot...is that connected to Notchmeister in some way?

**Comment by dmalachi** [comment]
Also, after reading over what logs and stats TestFlight would automatically send to you guys, I don't think my company NDAs would allow for me to run a TestFlight build and send log info. So I might have to wait to test until it's a public release.

**Comment by Gerzer** [comment]
> @dmalachi I'm curious if the latest TestFlight build solves this problem. Part of the problem with transient windows is that they get "activated".
> 
> With the new "Hide Dock icon" feature, there's no app to activate. In theory, this will prevent the settings window from appearing as spaces are switched.
> 
> Here's the TestFlight: https://testflight.apple.com/join/Nj8aKRvl

The TestFlight link that you provided is for your *other* Mac app! 😅

**Comment by chockenberry** [comment]
Yeah, whoops, wrong link. Here’s the correct one: https://testflight.apple.com/join/pIGViV74

@dmalachi Logs and other private info are not sent automatically. The only thing recorded is that you (anonymously) installed and launched the app. As with everything else Apple does, it very privacy oriented.

**Comment by chockenberry** [comment]
@dmalachi Does the most recent release on the App Store fix this problem? I'd like to close this issue.

**Comment by dmalachi** [comment]
Ah, very sorry. Haven't logged in on my laptop in a couple weeks. Let me update the app and get back to you shortly!

**Comment by dmalachi** [comment]
Yes, it seems the issue has been resolved with the latest release. Thank you!
