### ISSUE TITLE
"control panel" graphic appears when reconnecting to external displays

### ISSUE THREAD

**Issue by fastasleep** [chockenberry/Notchmeister#19]
![FQq-CetUcAIY3Y0](https://user-images.githubusercontent.com/476934/182742499-1cb2034e-8858-477d-bb8a-272ccd7ed1e0.png)

Solution is to quit and reopen. Happens I think every time I reconnect to external displays, which I do frequently at home and office. Above is example of reconnecting to my dual external displays. I get one of them when connecting to a single display. Thanks!

**Comment by chockenberry** [comment]
This should be fixed in the next release (now in the repo).
