### ISSUE TITLE
Notchmeister on Ventura is broken

### ISSUE THREAD

**Issue by bryceorchard** [chockenberry/Notchmeister#20]
### Summary
Ever since updating to macOS Ventura all effects are glitchy and unpredictable.
When the notchmeister app is in focus, all the effects work great, however when clicking away from the app and returning it to the background, the notch effects are very buggy.

### Issue
When dragging the mouse up to the notch while the app is minimized, the effects flickers on and off, particularily with the nano reader, which barely flips down.

### Video of issue
https://user-images.githubusercontent.com/92669537/196498431-12f539f0-01c2-492d-9266-dfd6b62a8564.mp4

### Version
macOS Ventura _(Version 13.0 Beta (22A5358e))_ 
Notchmeister _app store version 1.01_

**Comment by danielpunkass** [comment]
For what it's worth I was not able to reproduce this on my M1 Max MacBook Pro 14", running 13.0 (22A379). I tried light and dark modes, and several of the modules including Glow. I wonder if it has something to do with the particular monitor and/or graphics card on @Ultimatedude10's Mac?

**Comment by bryceorchard** [comment]
Seems to have been fixed on macOS 13.0 (22A380)
