### ISSUE TITLE
Question mark button suggests inaccessible help menu for getting to GitHub

### ISSUE THREAD

**Issue by ffried** [chockenberry/Notchmeister#22]
The question mark button suggests using the help menu for getting to this GitHub page. However, the help menu is inaccessible if the dock icon is hidden.
It might be a good idea to add a button or a link to this GitHub project in the dialog opened by the question mark button.

<img width="371" alt="image" src="https://github.com/chockenberry/Notchmeister/assets/1689782/07b60be9-a028-4be3-bb8a-999a48669259">

**Comment by chockenberry** [comment]
Yep, this will be fixed in the next release. Good catch!
