### ISSUE TITLE
New dice stay visible after moving mouse "through" the notch (often and) quick enough

### ISSUE THREAD

**Issue by ffried** [chockenberry/Notchmeister#23]
I have a dual monitor setup where my MacBook is in Front of a bigger external display. Thus the arrangement has the MacBook's display on the bottom and the external display at the top - allowing the mouse to move "through" the notch when transitioning to the external display.

When doing this a few times quickly with the dice model (in the TestFlight 1.0.4 (36) build), the dice will stay on screen.

https://github.com/chockenberry/Notchmeister/assets/1689782/a85f4f48-247b-4220-883d-2ab138c42d4d

**Comment by chockenberry** [comment]
This is a bug with Apple's mouse tracking code. All Mac apps that use tracking areas suffer from it: have you even noticed a tool tip that hangs around longer than it should? Same thing.

We tried hard to avoid it, but it's an unfortunate fact of life.

**Comment by ffried** [comment]
Oh, ok. Just found it strange that the other effects didn't seem to suffer from this. Or are they implemented differently?

**Comment by chockenberry** [comment]
Very differently - the previous ones used simple Core Animation. This new one uses a Metal scene with shaders, physics, etc. in a separate window that you can't click on, while another window tracks the mouse and clicks.

**Comment by ffried** [comment]
Interesting! Thanks for explaining!

**Comment by blackketter** [comment]
I can't reproduce this issue with the 1.0.5 (40) TestFlight build.  Wonder if the #25 fix also fixed this...

**Comment by ffried** [comment]
Yea, same here. Seems to be fixed!
