### ISSUE TITLE
Bug when screen resolution changes.

### ISSUE THREAD

**Issue by JackL6** [chockenberry/Notchmeister#3]
If you increase the amount of space on the display, Notchmeister displays halfway down the screen.

To reproduce:
Set Mac to default display resolution.
Start Notchmeister.
Set Mac to "more space" resolution.
Notice that Notchmeister is now 1/3 of the way down the screen from the top.

To resolve: restart Notchmeister.

**Comment by danielpunkass** [comment]
Thanks for reporting this. I was able to reproduce it easily by following the directions.
