### ISSUE TITLE
some (small) issues

### ISSUE THREAD

**Issue by justme-1968** [chockenberry/Notchmeister#4]
I really like this and during usage I have noticed some small issues:

- it would be great do hide the dock icon
- if the pointer is enlarged with the accessibility settings this is not reflected in the nano radar image
- i had a few instances where the nano radar does not hide if the mouse is not behind the notch anymore.
  this also happens with the other effects but I'm not sure when this happens. moving too fast or closing an app.

**Comment by chockenberry** [comment]
1) We're working on hiding the Dock icon (see issue #2).
2) As far as I know, there is no API to determine the size of the mouse pointer setting in Accessibility.
3) We're aware of the issue with Nano Radar not hiding correctly - there is _a lot_ going on here and the timing issue is hard to track down.
