### ISSUE TITLE
Cylon effect gets frozen/sends cursor to top-right of screen

### ISSUE THREAD

**Issue by chrismessina** [chockenberry/Notchmeister#5]
I have a dual-display setup:

![image](https://user-images.githubusercontent.com/22610/147621284-d7d37c79-af95-4566-9264-0ded121a621d.png)

When I use the Cylon visual effect, I've noticed several issues:

1. When I enter the notch area, the cylon animation freezes and sends my cursor to the top right corner of my non-MacBook Pro primary display
2. Once the cylon effect is frozen, a second cylon animation is triggered:

![2021-12-28 (18 21 29) Google Chrome](https://user-images.githubusercontent.com/22610/147621357-4a4a46b6-b9a5-4cf3-a6f4-e17b07a6f3b6.png)

**Comment by chockenberry** [comment]
I'm pretty sure this is related to issue #1 - some monitor configurations break the animations because the "we're under the notch" calculation is much harder.

**Comment by chrismessina** [comment]
> I'm pretty sure this is related to issue #1 - some monitor configurations break the animations because the "we're under the notch" calculation is much harder.

Could be...! I noticed this behavior on my MacBook Pro display though — not on my Pro XDR Display. I suppose if you're calculating a collision rectangle to determine where to show the effect, then indeed, perhaps the presence of a second display somehow confuses the coordinate system?

It would be clarifying if you could explain what the Cylon effect is supposed to do? Does it move the cursor somewhere if you enter the notch area?

**Comment by danielpunkass** [comment]
Likely related to #5

**Comment by chockenberry** [comment]
This issue should be fixed in the latest TestFlight build: https://testflight.apple.com/join/pIGViV74
