### ISSUE TITLE
Overlapping effects when Cylon effect selected

### ISSUE THREAD

**Issue by chrismessina** [chockenberry/Notchmeister#6]
I'm using the TestFlight build and it seems like when the [Cylon effect freezes](https://github.com/chockenberry/Notchmeister/issues/5), it doesn't disable the effect and allows other effects to run simultaneously:

![2021-12-28 (18 25 03) Notchmeister](https://user-images.githubusercontent.com/22610/147621687-348f4e50-c314-473f-95ce-a5efa7d80457.gif)

**Comment by chockenberry** [comment]
Again, we're back to issue #1.

The hardest part about fixing this bug is going to be replicating the external monitor configuration. Keep in mind that I don't have a MacBook Pro with a notch :-)

**Comment by danielpunkass** [comment]
I can take a look @chockenberry when I'm home from holiday travel. I have a 14" with Notch. I just tried to reproduce it and couldn't do so easily, though I did notice a little weird behavior if I click and drag while frozen at the Cyclon edge. I wonder if some action like that might have been involved in reproducing the problem originally @chrismessina ? Or can you reproduce it wihout clicking the mouse?

**Comment by danielpunkass** [comment]
(I should note though that at least at the moment I'm not connected to an external display. When I get home I'll be able to replicate a similar setup to Chris.)

**Comment by chrismessina** [comment]
> (I should note though that at least at the moment I'm not connected to an external display. When I get home I'll be able to replicate a similar setup to Chris.)

The second display seems like a critical aspect of what I'm experiencing. Happy to help debug further once you take a look @danielpunkass!

**Comment by danielpunkass** [comment]
Finally had a chance to start looking at these with a second display and I think I'm on the case. I'll take a swing at fixing this soon, along with several other tickets that I think are all related.

**Comment by chockenberry** [comment]
This issue should be fixed in the latest TestFlight build: https://testflight.apple.com/join/pIGViV74
