### ISSUE TITLE
Control Panel Visible Underneath Notch

### ISSUE THREAD

**Issue by Avakining** [chockenberry/Notchmeister#9]
The control panel seems to be bigger than the notch, and is this showing underneath it.

MacBook Pro 14", macOS 12.1, Notchmeister 1.0.1 (17)
![IMG_4190](https://user-images.githubusercontent.com/25210618/148255250-98e42b2d-d657-4b1a-b605-44ccd964eb29.jpg) (sorry for photo of screen, screenshots don't work obviously)

**Comment by chockenberry** [comment]
Yep, this is happening because we didn't realize that the size of the notch changes when you change screen scaling in System Prefs. Will be fixed in the next TestFlight.

**Comment by chockenberry** [comment]
Closing this issue now that a new TestFlight is out. If anyone finds an issue in 1.0.1 (18), I'll reopen it.
